name: employee_tracker
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  go_router: ^6.5.6
  hive: ^2.2.3
  intl: ^0.18.0
  calendar_date_picker2: ^0.5.2
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  flutter_svg: ^2.0.5
  

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/applogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/